micronaut:
  application:
    name: pocMicronautKotlinJwt
  security:
    endpoints:
      login:
        enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:OTk2NTE1fQ.6Uow2oGZ6mXGg_29aJ0OstDyLE8dg_05OpNF2NlUU8Q}"'
              jws-algorithm: HS256

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/anime
    driverClassName: org.postgresql.Driver
    username: root
    password: anime
    sql-dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true